- name: Cleanup
  hosts: local
  become: true
  tasks:
    - name: Remove packages
      pacman:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
    - name: Stop {{ app_service_name }}
      ansible.builtin.systemd:
        name: "{{ app_service_name }}"
        state: stopped
        enabled: false
    - name: Remove {{ app_service_name }}
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ app_service_name }}"
        state: absent
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Force delete Unit
      ansible.builtin.shell: systemctl reset-failed
    - name: Remove {{ app_dir }}/{{ app_file }}
      ansible.builtin.file:
        path: "{{ app_dir }}/{{ app_file }}"
        state: absent
    - name: Remove {{ app_user_id }} user
      ansible.builtin.user:
        name: "{{ app_user_id }}"
        state: absent
        remove: true
